#!/bin/sh

#xrandr --output DP-1 --mode 2560x1440 --rate 144
#xrandr --output DP-3 --right-of DP-1 --mode 1920x1080 --rate 144 --rotate left

xset -dpms
autorandr

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

. "${HOME}/.cache/wal/colors.sh"


# Set the border colors.
#spc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"

bspc config focused_border_color "$background"
bspc config normal_border_color  "$background"
bspc config active_border_color  "$background"
bspc config presel_feedback_color "$color2"

## Configurations -------------------------------#
bspc monitor DP-2 -d 'I' 'II' 'III' 'IV' 'V'
bspc monitor DP-0 -d 'VI' 'VII'

bspc config border_width 6
bspc config window_gap 15
bspc config split_ratio 0.5

bspc config border_radius 0


bspc config focused_border_color "$background"
bspc config normal_border_color  "$background"
bspc config active_border_color  "$background"
bspc config presel_feedback_color "$color2"

bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false


## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

bspc rule -a Onboard state=floating follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
bspc rule -a Zathura state=pseudo_tiled
bspc rule -a Wine state=floating manage=off
bspc rule -a Surf state=tiled manage=on

## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd dunst borders

borders &


# Launch daemons and shit
dunst -conf $HOME/.config/dunst/dunstrc &
sxhkd &
fixjava
# light-locker --lock-on-suspend &
# nm-applet & 
# openrazer-daemon
# sleep 0.1
# razer-cli -e spectrum

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -xcf $HOME/.icons/Quintom_Ink/cursors/left_ptr 25

# Start bspwm scripts
#bspcolors
bspcomp
bspfloat &
numlockx on

walset -p $HOME/Pictures/omori/pain.jpg -b colorthief &> /dev/null
. "${HOME}/.cache/wal/colors.sh"

~/.config/polybar/manhattan/launch.sh &

startpage & 

