
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-12-12T08:17:03-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "58ef3da9aa99469ef114c9e1ab3a24ebcb325a7d",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
